### ISSUE TITLE
Plugin Doesn't work on newer Substance Painter versions

### ISSUE THREAD

**Issue by Caseter** [emomilol1213/Substance-Painter-DDS-Exporter#1]
The plugin throws erorrs if you try to use on newer versions. I'm currently on 9.0.1 and receive the below errors:

![image](https://github.com/emomilol1213/Substance-Painter-DDS-Exporter/assets/145297083/ee42ae37-5c10-49b6-b3f3-b58ba1ec925e)

**Comment by emomilol1213** [comment]
Fixed in version 0.1.1
